server:
  port: 8020
  
spring:
  application:
    name: microservice-consumer-goods
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/
instance:
  prefer-ip-address: true