server:
  port: 9020
  
spring:
  application:
    name: microservice-goods
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-eureka:9000/eureka/
instance:
  prefer-ip-address: true