spring:
  application:
    name: microservice-discovery-eureka-ha
    
---  
spring:
  profiles: discovery-eureka-a
server:
  port: 9000
eureka:
  instance:
    hostname: discovery-eureka-a
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-eureka-b:9001/eureka/

---
spring:
  profiles: discovery-eureka-b
server:
  port: 9001
eureka:
  instance:
    hostname: discovery-eureka-b
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-eureka-a:9000/eureka/
      